# Generated by Django 5.1.2 on 2024-12-13 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=8, unique=True)),
                ('creator_name', models.CharField(max_length=100)),
                ('rounds', models.IntegerField(choices=[(5, '5'), (7, '7'), (10, '10')])),
                ('scoring_method', models.CharField(choices=[('Score Each Other', 'Score Each Other'), ('Score Yourself', 'Score Yourself')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
            ],
        ),
    ]
