# Generated by Django 5.1.2 on 2024-12-13 04:19

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='letter',
            field=models.CharField(default=game.models.get_random_letter, max_length=1),
        ),
    ]
